#include <MEP-3D/key_event.hpp>

namespace mep {
std::string KeyToString(Key Key) {
  switch (Key) {
    case Key::A:
      return "A";
    case Key::B:
      return "B";
    case Key::C:
      return "C";
    case Key::D:
      return "D";
    case Key::E:
      return "E";
    case Key::F:
      return "F";
    case Key::G:
      return "G";
    case Key::H:
      return "H";
    case Key::I:
      return "I";
    case Key::J:
      return "J";
    case Key::K:
      return "K";
    case Key::L:
      return "L";
    case Key::M:
      return "M";
    case Key::N:
      return "N";
    case Key::O:
      return "O";
    case Key::P:
      return "P";
    case Key::Q:
      return "Q";
    case Key::R:
      return "R";
    case Key::S:
      return "S";
    case Key::T:
      return "T";
    case Key::U:
      return "U";
    case Key::V:
      return "V";
    case Key::W:
      return "W";
    case Key::X:
      return "X";
    case Key::Y:
      return "Y";
    case Key::Z:
      return "Z";
    case Key::Space:
      return "Space";
    case Key::Apostrophe:
      return "Apostrophe";
    case Key::Comma:
      return "Comma";
    case Key::Minus:
      return "Minus";
    case Key::Period:
      return "Period";
    case Key::Slash:
      return "Slash";
    case Key::Key0:
      return "Key0";
    case Key::Key1:
      return "Key1";
    case Key::Key2:
      return "Key2";
    case Key::Key3:
      return "Key3";
    case Key::Key4:
      return "Key4";
    case Key::Key5:
      return "Key5";
    case Key::Key6:
      return "Key6";
    case Key::Key7:
      return "Key7";
    case Key::Key8:
      return "Key8";
    case Key::Key9:
      return "Key9";
    case Key::Semicolon:
      return "Semicolon";
    case Key::Equal:
      return "Equal";
    case Key::LeftBracket:
      return "LeftBracket";
    case Key::Backslash:
      return "Backslash";
    case Key::RightBracket:
      return "RightBracket";
    case Key::Accent:
      return "Accent";
    case Key::Escape:
      return "Escape";
    case Key::Enter:
      return "Enter";
    case Key::Tab:
      return "Tab";
    case Key::Backspace:
      return "Backspace";
    case Key::Insert:
      return "Insert";
    case Key::Delete:
      return "Delete";
    case Key::RightArrow:
      return "RightArrow";
    case Key::LeftArrow:
      return "LeftArrow";
    case Key::DownArrow:
      return "DownArrow";
    case Key::UpArrow:
      return "UpArrow";
    case Key::CapsLock:
      return "CapsLock";
    case Key::F1:
      return "F1";
    case Key::F2:
      return "F2";
    case Key::F3:
      return "F3";
    case Key::F4:
      return "F4";
    case Key::F5:
      return "F5";
    case Key::F6:
      return "F6";
    case Key::F7:
      return "F7";
    case Key::F8:
      return "F8";
    case Key::F9:
      return "F9";
    case Key::F10:
      return "F10";
    case Key::F11:
      return "F11";
    case Key::F12:
      return "F12";
    case Key::F13:
      return "F13";
    case Key::F14:
      return "F14";
    case Key::F15:
      return "F15";
    case Key::F16:
      return "F16";
    case Key::F17:
      return "F17";
    case Key::F18:
      return "F18";
    case Key::F19:
      return "F19";
    case Key::F20:
      return "F20";
    case Key::LeftShift:
      return "LeftShift";
    case Key::LeftControl:
      return "LeftControl";
    case Key::LeftAlt:
      return "LeftAlt";
    case Key::LeftSuper:
      return "LeftSuper";
    case Key::RightShift:
      return "RightShift";
    case Key::RightControl:
      return "RightControl";
    case Key::RightAlt:
      return "RightAlt";
    case Key::RightSuper:
      return "RightSuper";
    case Key::MouseLeft:
      return "MouseLeft";
    case Key::MouseRight:
      return "MouseRight";
    case Key::MouseMiddle:
      return "MouseMiddle";
    case Key::Mouse1:
      return "Mouse1";
    case Key::Mouse2:
      return "Mouse2";
    case Key::Mouse3:
      return "Mouse3";
    case Key::Mouse4:
      return "Mouse4";
    case Key::Mouse5:
      return "Mouse5";
    case Key::UnknownKey:
      return "UnknownKey";
  }
}
}  // namespace mep
